---
- block:
  - name: get mattermost package
    unarchive:
      src: "https://releases.mattermost.com/{{ mattermost_version }}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"
      dest: "/opt"
      owner: root
      group: root
      mode: "0755"
      remote_src: "yes"
  - name: rename mattermost path to appropriate path
    command: "mv /opt/mattermost '{{ mattermost_root_dir }}'"
    args:
      creates: "{{ mattermost_root_dir }}"
      removes: "/opt/mattermost"
  - name: setup mariadb fulltext index
    copy:
      src: "mattermost.cnf"
      dest: "/etc/mysql/conf.d/mattermost.cnf"
      owner: root
      group: root
      mode: "0644"
  - name: restart mariadb service
    service: "name=mariadb.service state=restarted"
  - name: create mattermost database
    shell: "mysql -uroot -e 'CREATE DATABASE {{ mattermost_db_name }} CHARSET utf8mb4'"
  - name: setup db user and password
    shell: "mysql -uroot -e 'GRANT ALL ON {{ mattermost_db_name }}.* TO \"{{ mattermost_db_user }}\"@\"localhost\" IDENTIFIED BY \"{{ mattermost_db_password }}\"'"
  - name: create mattermost group account
    group:
      name: "{{ mattermost_group }}"
      state: "present"
  - name: create mattermost user account
    user:
      name: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
  - name: setup mattermost dir permissions
    file:
      path: "{{ mattermost_root_dir }}/{{ item }}"
      owner: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
      mode: "0700"
      state: directory
    loop:
      - "data"
      - "logs"
      - "plugins"
  - name: setup mattermost config DataSource
    replace:
      path: "{{ mattermost_root_dir }}/config/config.json"
      regexp: '"DataSource": "[^"]*"'
      replace: '"DataSource": "{{ mattermost_db_user }}:{{ mattermost_db_password }}@tcp(localhost:3306)/{{ mattermost_db_name }}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"'
  - name: setup mattermost config ListenAddress
    replace:
      path: "{{ mattermost_root_dir }}/config/config.json"
      regexp: '"ListenAddress": "[^"]*"'
      replace: '"ListenAddress": ":{{ mattermost_port }}"'
  - name: setup mattermost config permission
    file:
      path: "{{ mattermost_root_dir }}/config/config.json"
      owner: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
      mode: "0600"
  - name: setup mattermost systemd service
    template:
      src: "mattermost.service.j2"
      dest: "/etc/systemd/system/{{ mattermost_team_name }}_mattermost.service"
      owner: root
      group: root
      mode: "0644"
  - name: reload systemd service
    command: "systemctl daemon-reload"
  - name: enable mattermost service
    command: "systemctl enable {{ mattermost_team_name }}_mattermost.service"
  - name: start mattermost service
    command: "systemctl start {{ mattermost_team_name }}_mattermost.service"
  - name: install nginx production config
    template:
      src: "nginx_production.conf.j2"
      dest: "/etc/nginx/sites-available/{{ mattermost_domain_name }}.conf"
      owner: root
      group: root
      mode: "0644"
  - name: reload nginx
    command: "systemctl reload nginx"
  - name: setup db index
    script: "alter_db_index.sh {{ mattermost_db_name }}"
  tags:
    - mattermost
