---
- block:
  - name: make sure the dest dir exists
    file:
      path: "{{ mattermost_root_dir }}"
      state: directory
      mode: "0755"
  - name: get mattermost package
    unarchive:
      src: "https://releases.mattermost.com/{{ mattermost_version }}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"
      dest: "{{ mattermost_root_dir }}"
      owner: root
      group: root
      mode: "0755"
      remote_src: "yes"
  - name: setup mysql fulltext index
    copy:
      src: "mattermost.cnf"
      dest: "/etc/mysql/conf.d/mattermost.cnf"
      owner: root
      group: root
      mode: "0644"
  - name: restart mysql service
    service: "name=mysql.service state=restarted"
  - name: create mattermost database
    shell: "mysql -u'root' -p'{{ percona_root_password }}' -e 'CREATE DATABASE {{ mattermost_db_name }} CHARSET utf8mb4'"
  - name: setup db user and password
    shell: "mysql -u'root' -p'{{ percona_root_password }}' -e 'GRANT ALL ON {{ mattermost_db_name }}.* TO \"{{ mattermost_db_user }}\"@\"localhost\" IDENTIFIED BY \"{{ mattermost_db_password }}\"'"
  - name: create mattermost group account
    group:
      name: "{{ mattermost_group }}"
      state: "present"
  - name: create mattermost user account
    user:
      name: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
  - name: create mattermost data dir
    file:
      path: "{{ mattermost_root_dir }}/data"
      owner: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
      mode: "0700"
      state: directory
  - name: setup log dir permission
    file:
      path: "{{ mattermost_root_dir }}/logs"
      owner: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
      mode: "0700"
      state: directory
  - name: setup mattermost config DataSource
    replace:
      path: "{{ mattermost_root_dir }}/config/config.json"
      regexp: '"DataSource": "[^"]*"'
      replace: '"DataSource": "{{ mattermost_db_user }}:{{ mattermost_db_password }}@tcp(localhost:3306)/{{ mattermost_db_name }}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s"'
  - name: setup mattermost config permission
    file:
      path: "{{ mattermost_root_dir }}/config/config.json"
      owner: "{{ mattermost_user }}"
      group: "{{ mattermost_group }}"
      mode: "0600"
  - name: setup mattermost systemd service
    template:
      src: "mattermost.service.j2"
      dest: "/etc/systemd/system/mattermost.service"
      owner: root
      group: root
      mode: "0644"
  - name: reload systemd service
    command: "systemctl daemon-reload"
  - name: enable mattermost service
    command: "systemctl enable mattermost.service"
  - name: start mattermost service
    command: "systemctl start mattermost.service"
  tags:
    - mattermost
